name: Terraform Azure Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # 🔐 Azure Login using GitHub Secrets
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ 2e01ea6c-fb1f-429b-8c06-30ccff14fded }}
          tenant-id: ${{ 2a12578d-9130-4f98-9fe6-c8a422505a24 }}
          subscription-id: ${{ 2b0a7e07-53fd-47f9-85cf-6fbc0364e35f }}
          client-secret: ${{ fhH8Q~1lLm5.voO~0.czvweDVTnPnLfII8vzgdc1 }}

      # ✅ Terraform Init
      - name: Terraform Init
        run: terraform init

      # ✅ Format Check
      - name: Terraform Format Check
        run: terraform fmt

      # ✅ Validate
      - name: Terraform Validate
        run: terraform validate

      # ✅ Plan
      - name: Terraform Plan
        run: terraform plan

      # ⚠️ Apply (manual safety recommended in real projects)
      - name: Terraform Apply
        run: terraform apply -auto-approve
